### ISSUE TITLE
perl-db-hts doesn't find htslib library, issue with htslib package

### ISSUE THREAD

**Issue by matthdsm** [bioconda/bioconda-recipes#4783]
Hi there

I'm having some issues with my install of the perl-bio-db-hts package. When I try to load module `Bio::DB::HTS::Faidx` I get the following error:

```
[node] work $ perl -MBio::DB::HTS::Faidx -e 'print $MODULE::VERSION'                                                                                                                                                                                                                                                                                                                                               [9:09:59]
Can't load /anaconda/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/auto/Bio/DB/HTS/Faidx/Faidx.so' for module Bio::DB::HTS::Faidx: libhts.so.1: cannot open shared object file: No such file or directory at /anaconda/lib/perl5/5.22.0/XSLoader.pm line 70.
 at /anaconda/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/Bio/DB/HTS/Faidx.pm line 87.
Compilation failed in require.
BEGIN failed--compilation aborted.
```
This issue arose since installing htslib 1.4.1. Works fine with htslib 1.3
ping @bioconda/perl

**Comment by chapmanb** [comment]
Matthias;
htslib 1.4.x and 1.3.x have different library versions (`.so.2` and `.so.1`, respectively), leading to this incompatibility. We need to rebuild the perl module with the latest version. Sorry you're stuck on this, I can take a look to see if I can get the module up to date.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks, I'm already trying to do so myself, but I'm having some compile issues. Perhaps you're better suited to fix this than I am.

Thanks again.
M

**Comment by johanneskoester** [comment]
In particular, the package should pin the htslib version used for the build.

**Comment by matthdsm** [comment]
I temporarily pinned the htslib version in the ensembl-vep  recipe, so that one's usable again.
We can leave it like this untill a solution if found for the issue above.

M

**Comment by chapmanb** [comment]
Matthias;
I pushed new versions of perl-bio-db-hts and ensembl-vep that build and pin against htslib 1.4 so this should now work and be compatible with the rest of the bioconda packages. The PR fix is #4793

**Comment by matthdsm** [comment]
Allright! Thanks Brad,
I'll start testing right away.

M
