### PR TITLE
Bump sambamba to 0.6.7 (-L flag support)

### PR DESCRIPTION
**Pull request by brainstorm**
* [x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [x] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by brainstorm** [comment]
Hm, requires D compiler:

```
+ set -eu
+ make
which: no ldmd2 in (/opt/conda/conda-bld/sambamba_1525230213594/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/opt/conda/conda-bld/sambamba_1525230213594/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac:/opt/conda/conda-bld/sambamba_1525230213594/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/root/project/miniconda/bin:/opt/conda/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
./gen_ldc_version_info.py  > utils/ldc_version_info_.d
make: *** [ldc-version-info] Error 1
BUILD START: sambamba-0.6.7-0
    (actual version deferred until further download or env creation)
Source cache directory is: /opt/conda/conda-bld/src_cache
Downloading source to cache: sambamba_v0.6.7.tar.bz2
Downloading https://github.com/biod/sambamba/archive/v0.6.7.tar.gz
Success
Extracting download
BUILD START (revised): sambamba-0.6.7-0
Package: sambamba-0.6.7-0
source tree in: /opt/conda/conda-bld/sambamba_1525230213594/work/sambamba-0.6.7
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1524, in build_tree
    config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1147, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/opt/conda/conda-bld/sambamba_1525230213594/work/sambamba-0.6.7/conda_build.sh']' returned non-zero exit status 2.
```

This is going to be a tough one to bump up and compile from source since the original repo where binaries where released is gone.

**Comment by bgruening** [comment]
@brainstorm is the D compiler now part of GCC?

**Comment by brainstorm** [comment]
Taking the gitter.im discussion here:

> I was trying to bump up sambamba on bioconda (bioconda/bioconda-recipes#8787) but then I realized that it requires D's compiler ldc (https://github.com/ldc-developers/ldc)... would it make sense to package ldc into bioconda or conda-forge or is it something that should ideally be in the CI machine images for other packages written in D?

Good point @bgruening, googling a bit I saw this:

http://dgcc.sourceforge.net/

But then it seems like LLVM D backend is also needed in the `Makefile` (not only for OSX afaict?):

https://github.com/biod/sambamba#compile

While it states that compiling is discouraged I disagree since bioconda's CI automatically generates conda packages for all targets (OSX, Linux and so on) when it succeeds... i.e, one drawback of not compiling is that OSX release is not generated for 0.6.7 since the release process is still manual, I guess.

Best to ask actual D and sambamba experts like @pjotrp and past package mantainer, @chapmanb for if and how to ship/use a D compiler in @bioconda/build-system?

**Comment by pjotrp** [comment]
This is a long standing discussion. I agree that building from source is the preferred option, but most people find it bothersome to install the D compiler and make the build work with htslib etc. I actually manage a package definition for GNU Guix [here](https://gitlab.com/genenetwork/guix-bioinformatics/blob/master/gn/packages/sambamba.scm) which I use for build testing and deployment. You could take that as a template.

At this point sambamba has the best performance with ldc 1.7.x and a recent LLVM. I have not tested with the GNU D compiler, but it is known the LLVM compiler has very agressive optimizations.

There is a pre-built binary distribution for sambamba at https://github.com/biod/sambamba/releases, but I only supply the Linux edition. If someone feels like creating an OSX binary edition I could put it up on github. That could be the lazy option.

**Comment by brainstorm** [comment]
@bgruening `gdc`, the GNU D compiler is not present, at least on the `circleci build` local docker image:


```
gdc -singleobj -wi -I. -IBioD -IundeaD/src -g -O3 -release -enable-inlining 
-boundscheck=off -c -of=build/sambamba.o main.d 
utils/lz4.d utils/strip_bcf_header.d utils/version_.d 
thirdparty/mergesort.d thirdparty/unstablesort.d 
cram/exception.d cram/htslib.d cram/reader.d 
cram/reference.d cram/slicereader.d cram/wrappers.d 
cram/writer.d undeaD/src/undead/bitarray.d (...)

make: gdc: Command not found
make: *** [singleobj] Error 127

WARNING: conda-build appears to be out of date. You have version 2.1.18 but the
```

So, what's the process of including it on the official bioconda builds (either GNU D and/or LLVM's LDC)?

**Comment by isuruf** [comment]
@pjotrp, do you have a binary of ldc2 compiled for CentOS 6?

**Comment by pjotrp** [comment]
There should be one on the dlang.org site. Can you not find it?

**Comment by brainstorm** [comment]
Sorry for the noise and no worries @pjotrp, thanks to Isuru's perseverance we have a working LDC for all platforms (linux/osx/win) uploaded at conda-forge as of today.

Now there's an compiling issue with [BioD itself upstream it seems](https://travis-ci.org/biod/sambamba/jobs/378025288#L602) :-S

**Comment by pjotrp** [comment]
Pull in BioD latest in the BioD folder. I am no longer using git submodules.

**Comment by brainstorm** [comment]
@pjotrp You mean https://github.com/biod/biod on `master` branch? That build is failing with [the same error as sambamba's TravisCI, afaict](https://travis-ci.org/biod/BioD/jobs/378304326#L472) :-S. Having a look at the commits now to see when that compiling error was introduced in master...

**Comment by pjotrp** [comment]
On Tue, May 15, 2018 at 02:51:44PM +0000, Roman Valls Guimerà wrote:
>    [1]@pjotrp You mean [2]https://github.com/biod/biod on master branch?
>    That build is failing with [3]the same error as sambamba's TravisCI,
>    afaict :-S. Having a look at the commits now to see when that compiling
>    error was introduced in master...

Ah, sorry. Problem is that I have not used ldc 1.7. Yet. I'll look
into it, but it has to wait because I am on poor internet this week.
On my list.

Pj.

**Comment by brainstorm** [comment]
Thanks Pjotr, much appreciated, thanks for mantaining this project! Just so you know I have a PR opened to support sambamba slice on SnakeMake wrappers:

https://bitbucket.org/snakemake/snakemake-wrappers/pull-requests/32/sambamba-slice/diff

Slices BAMs with BEDs waay faster than anything else ;)

I wish I knew better about D types inference and help you out with that one :-/

**Comment by pjotrp** [comment]
@brainstorm I'll look into this next week. Sorry, have been crazy busy.

File: recipes/sambamba/meta.yaml [hunk 1]
```diff
@@ -1,23 +1,40 @@
...
+  git_url: https://github.com/biod/sambamba
+  git_rev: {{ revision }}
+  md5: unused
 
-build:
-  number: 1
+requirements:
+  build:
+    - ldc
+    - gcc
```
Comment (marcelotrevisani) [inline recipes/sambamba/meta.yaml]: Did you try to use conda build 3?
Like, replace gcc for:
```
- {{ compiler('c') }}
```

File: recipes/sambamba/meta.yaml [hunk 2]
```diff
@@ -1,23 +1,40 @@
...
+    - bzip2 {{ CONDA_BZIP2 }}*
+    - zlib {{ CONDA_ZLIB }}*
+    - xz {{ CONDA_XZ }}*
+  run:
+    - libgcc
```
Comment (marcelotrevisani) [inline recipes/sambamba/meta.yaml]: and this part of ``- libgcc`` will not be necessary

File: recipes/sambamba/meta.yaml (hunk 1 above)
Comment (brainstorm) [reply recipes/sambamba/meta.yaml]: I tried/changed the Makefile to accommodate GDC, but quite a few changes were required and Pjotr mentioned that LDC had more optimizations anyway (see comments above).

**Comment by brainstorm** [comment]
@pjotrp Thanks a lot and no worries, I really appreciate your efforts and patience ;)

**Comment by pjotrp** [comment]
Still some problems with sorting, but at least sambamba compiles again with ldc 1.10.0

**Comment by pjotrp** [comment]
@brainstorm sambamba should compile again and test pass. Note that BioD should be symlinked in as well as unDead. htslib is still a submodule. I need to think how I am going to handle that. I'll see if I can fix a few more bugs and get a release out soonish. Upgrading htslib will be after. I don't think many people are using CRAM with sambamba right now.

**Comment by brainstorm** [comment]
Thanks a lot @pjotrp for following up on this (and related issues)! I was just about to put the revision in the recipe over here, but I'm seeing some build issues on sambamba travis from 3h ago, so I guess you're fighting to get the last wrinkles flattened out?

From the looks of it right now, it seems like [LZ4](https://travis-ci.org/biod/sambamba/jobs/409634726#L719) lib is having some linking issues. I'll take a look back into it later, @-mention me again if you need more help ironing those out ;)

**Comment by pjotrp** [comment]
liblz4.so is not found - I need to add a search path to pick it up on Ubuntu in travis. We are getting close!

**Comment by pjotrp** [comment]
Btw I reintroduced git submodules for undeaD and BioD. It is the easy option and as I am the only active developer it is not a big deal.

**Comment by pjotrp** [comment]
Debian moved liblz4 to /usr/lib/x86_64-linux-gnu/liblz4.so.

**Comment by pjotrp** [comment]
Hmmm. Adding paths does not help. Must be a new mapping thing between D and C code not working on Debian (it works on GNU Guix). More later.

**Comment by pjotrp** [comment]
It is actually methods missing in liblz4.so (you can see the Travis output). Grrrr.

**Comment by pjotrp** [comment]
The API got changed. Need to find the right package https://groups.google.com/forum/#!topic/linux.debian.devel.release/n0pFUaunGco

**Comment by pjotrp** [comment]
lz4frame.h is missing from recent Debian/Ubuntu packages. There appears to be no replacement package for lz4f. This means I have to build lz4 from source again for Debian. What are they thinking? Is lz4frame.h in bioconda? Probably.

**Comment by pjotrp** [comment]
We have a building sambamba on travis after reintroducing lz4 source tree. Please give it a shot.

**Comment by pjotrp** [comment]
@brainstorm why is the test failing? Appears to be a conda thing. I'll fix the unit/regression tests also - just need to a shunit2 to the source tree. It is a small thing. The shunit2 in Debian is a later version and they broke backwards compatibility ages ago. I'll also fix the MacOS build.

File: recipes/sambamba/meta.yaml [hunk 3]
```diff
@@ -1,22 +1,38 @@
...
+  md5: unused
 
-build:
-  number: 2
+requirements:
+  build:
+    - ldc
+    - bzip2 {{ CONDA_BZIP2 }}*
+    - zlib {{ CONDA_ZLIB }}*
+    - xz {{ CONDA_XZ }}*
```
Comment (johanneskoester) [inline recipes/sambamba/meta.yaml]: This jinja2-syntax was a bioconda-specific way to pin dependencies which is now outdated with the switch to conda-build 3. You can simply use the names of the libs here and in run, and pinning will happen automatically.

Moreover, use `host`  instead of build, and add the compiler to the build section. See the bwa recipe for an example: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bwa/meta.yaml

Comment (brainstorm) [reply recipes/sambamba/meta.yaml]: Thanks a lot Johannes, much appreciated! :)

I set the compiler to `ldc` but the build failed: https://circleci.com/gh/bioconda/bioconda-recipes/20195 ... I'll try now with just compiler('c') since I believe there's the C bits (lz4, htslib, etc...) that might require that directive (guessing on the internals of conda-build 3)...

Comment (brainstorm) [reply recipes/sambamba/meta.yaml]: @johanneskoester, After removing the pinning, zlib doesn't seem to be found automatically:

https://circleci.com/gh/bioconda/bioconda-recipes/20201

```bash
cd lz4/lib && gcc -O3 -c lz4.c lz4hc.c lz4frame.c xxhash.c && ar rcs liblz4.a lz4.o lz4hc.o lz4frame.o xxhash.o
cd htslib && make
make[1]: Entering directory `/opt/conda/conda-bld/sambamba_1533083071240/work/htslib'
gcc -g -Wall -O2 -D_GNU_SOURCE -I.  -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -D_GNU_SOURCE -I.  -c -o knetfile.o knetfile.c
gcc -g -Wall -O2 -D_GNU_SOURCE -I.  -c -o kstring.o kstring.c
echo '/* Empty config.h generated by Makefile */' > config.h
gcc -g -Wall -O2 -D_GNU_SOURCE -I.  -c -o bgzf.o bgzf.c
In file included from bgzf.c:39:0:
htslib/bgzf.h:34:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
make[1]: *** [bgzf.o] Error 1
make[1]: Leaving directory `/opt/conda/conda-bld/sambamba_1533083071240/work/htslib'
make: *** [htslib-static] Error 2
```

**Comment by pjotrp** [comment]
Note sambamba current builds fine on ldc 1.10. I'll fix ldc 1.11 soon.

**Comment by brainstorm** [comment]
It's just the zlib issue remaining AFAICT, I recall fixing it a few weeks ago myself on the Makefile's LDFLAGS & co, I should have kept the commit/notes on that :/ ... will check later next week.

**Comment by pjotrp** [comment]
Sambamba Travis-CI build is passing for ldc 1.10 and 1.11! I'll do a release soon. Note you need llvm6 for best performance.

**Comment by pjotrp** [comment]
I just released sambamba 0.6.8 and BioD 0.2.1 which should compile with recent ldc compilers. I can help resolve any outstanding issues.

**Comment by brainstorm** [comment]
@pjotrp I just bumped the version/revision and at this moment it seems that the only issue left to fix is the `zlib` issue:

https://circleci.com/gh/bioconda/bioconda-recipes/28523

I guess that a `pkg-config --libs` or similar is required in the Makefile, sorry I have had not much time to look into it lately :/

**Comment by brainstorm** [comment]
Also on OSX there's some issues too, investigating...:

```
(...)
ldc2 -wi -I. -IBioD -IundeaD/src -g -O3 -release -enable-inlining -boundscheck=off -of=bin/sambamba bin/sambamba.o  htslib/libhts.a lz4/lib/liblz4.a -L-L -L-lpthread -L-lm
ld: warning: directory not found for option '-L-lpthread'
Undefined symbols for architecture x86_64:
  "__D5utils17ldc_version_info_18DMD_VERSION_STRINGyAa", referenced from:
      __D4main12printVersionFZv in sambamba.o
  "__D5utils17ldc_version_info_18LDC_VERSION_STRINGyAa", referenced from:
      __D4main12printVersionFZv in sambamba.o
  "__D5utils17ldc_version_info_19LLVM_VERSION_STRINGyAa", referenced from:
      __D4main12printVersionFZv in sambamba.o
  "__D5utils17ldc_version_info_24BOOTSTRAP_VERSION_STRINGyAa", referenced from:
      __D4main12printVersionFZv in sambamba.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: /usr/bin/gcc failed with status: 1
make: *** [bin/sambamba] Error 1
```

**Comment by brainstorm** [comment]
There seems to be more reliable ways to pass those linker flags to `ldc`, apparently:

https://github.com/ldc-developers/ldc/issues/1700#issuecomment-295045679

Perhaps via `-Xcc pthreads` or similar special LDC flag?:

https://github.com/epi/ldc/commit/62c7987bfaf250130d56f7b98ebadf38c71063b1

Using LDC 1.11 right now, btw.

**Comment by dpryan79** [comment]
I just merged 0.6.8 in, so this is likely no longer needed.

**Comment by brainstorm** [comment]
Alright, I think I see part of the problem. It would be great if the `LIBRARY_PATH` defined in the `Makefile` and [mentioned in the install docs](https://github.com/biod/sambamba#compiling-for-mac-os-x) is determined at compile time instead of having to be set manually per-OS:

https://github.com/biod/sambamba/blob/master/.travis.yml.macos#L18

**Comment by brainstorm** [comment]
@dpryan79 Which PR is that?

**Comment by dpryan79** [comment]
@brainstorm https://github.com/bioconda/bioconda-recipes/pull/11212

**Comment by brainstorm** [comment]
Cool, closing then. Thanks everyone!
