### ISSUE TITLE
groopM recipe is broken

### ISSUE THREAD

**Issue by jvollme** [bioconda/bioconda-recipes#36359]
The groopM recipe includes bamm as a dependency. The corresponding bamm recipe includes python >= 2.7 as dependency. However groopM does not work with python >= 2.7 but requires very old python versions.

Attempting to run groopM installed via conda on any actual datasets results in the following error:
```AttributeError: 'module' object has no attribute 'openFile'```

The problem is, among others, that openFile was discontinued some time ago. Therefore the groopM recipe requires it`s own bamm recipe that can use older python versions.
