### ISSUE TITLE
 Build failure for immuneml recipe on PR #52702

### ISSUE THREAD

**Issue by pavelvazquez** [bioconda/bioconda-recipes#52732]
The immuneml build ([PR #52702](https://github.com/bioconda/bioconda-recipes/pull/52702)) suddenly fails with:

AttributeError: module 'lief._lief.ELF' has no attribute 'DYNAMIC_TAGS'
CondaKeyError: 'channels': value 'defaults' not present in config

This recipe built fine before and still builds locally without issues. I notice other recent PRs are hitting the same lief error. Could recent CI environment changes, conda-build, or lief updates have caused this regression?

Any guidance would be appreciated.

**Comment by martin-g** [comment]
It was caused by https://github.com/conda-forge/lief-feedstock/pull/49
It is fixed now!
