### PR TITLE
Update adam to 1.0

### PR DESCRIPTION
**Pull request by heuermh**
Describe your pull request here

----

Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull request (PR).

* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its title.
* New recipes not directly relevant to the biological sciences need to be submitted to the [conda-forge channel](https://conda-forge.org/docs/) instead of Bioconda.
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue the `@BiocondaBot please add label` command.
* Please post questions [on Gitter](https://gitter.im/bioconda/Lobby) or ping `@bioconda/core` in a comment.

<details>
  <summary>Please use the following BiocondaBot commands:</summary>

Everyone has access to the following BiocondaBot commands, which can be given in a comment:

<table>
  <tr>
    <td><code>@BiocondaBot please update</code></td>
    <td>Merge the master branch into a PR.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please add label</code></td>
    <td>Add the <code>please review & merge</code> label.</td>
  </tr>
  <tr>
    <td><code>@BiocondaBot please fetch artifacts</code></td>
    <td>Post links to CI-built packages/containers. <br />You can use this to test packages locally.</td>
  </tr>
</table>

For members of the Bioconda project, the following command is also available:

<table>
  <tr>
    <td><code>@BiocondaBot please merge</code></td>
    <td>Upload built packages/containers and merge a PR. <br />Someone must approve a PR first! <br />This reduces CI build time by reusing built artifacts.</td>
  </tr>
</table>

Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will automatically re-post them to notify the addressed `<team>`.

</details>

### CODE REVIEW

**Comment by heuermh** [comment]
I'm not sure what the failures here are about, CI looks quite different than the last time. This pull request is simply a version bump and shouldn't cause any CI failures.

**Comment by heuermh** [comment]
Tests appear to be running ok, what is the failure from?
```
2022-05-27T01:14:37.5455019Z 01:14:37 BIOCONDA INFO (OUT) + adam-submit --help
...
2022-05-27T01:14:39.7744087Z 01:14:39 BIOCONDA INFO (OUT) 
2022-05-27T01:14:39.7830207Z INFO:bioconda_utils.utils:(OUT)        e        888~-_         e            e    e
2022-05-27T01:14:39.7869648Z INFO:bioconda_utils.utils:(OUT)       d8b       888   \       d8b          d8b  d8b
...
2022-05-27T01:14:39.8408567Z INFO:bioconda_utils.utils:(OUT) + exit 0
2022-05-27T01:14:39.8409017Z 01:14:39 BIOCONDA INFO (OUT) + exit 0
...
2022-05-27T01:14:41.4611036Z 01:14:41 BIOCONDA INFO (OUT) 
2022-05-27T01:14:41.4611635Z 01:14:41 BIOCONDA INFO (OUT) Resource usage statistics from testing adam:
2022-05-27T01:14:41.4612207Z 01:14:41 BIOCONDA INFO (OUT)    Process count: 4
2022-05-27T01:14:41.4612813Z 01:14:41 BIOCONDA INFO (OUT)    CPU time: Sys=0:00:00.2, User=0:00:02.0
2022-05-27T01:14:41.4613387Z 01:14:41 BIOCONDA INFO (OUT)    Memory: 141.2M
2022-05-27T01:14:41.4613931Z 01:14:41 BIOCONDA INFO (OUT)    Disk usage: 20B
2022-05-27T01:14:41.4614467Z 01:14:41 BIOCONDA INFO (OUT)    Time elapsed: 0:00:04.3
```

**Comment by heuermh** [comment]
Ah ha!  Further down, the dependency version for pyspark is incorrect, it is `2.4.4` with Scala version 2.11 whereas it should be `3.2.1` with Scala version 2.12
```
2022-05-27T01:19:29.5165715Z INFO:bioconda_utils.utils:(ERR) [May 27 01:19:29] SOUT pyspark            conda-forge/noarch::pyspark-2.4.4-py_0
2022-05-27T01:19:29.5166504Z 01:19:29 BIOCONDA INFO (ERR) [May 27 01:19:29] SOUT pyspark            conda-forge/noarch::pyspark-2.4.4-py_0
...
2022-05-27T01:21:37.2818227Z 01:21:37 BIOCONDA INFO (ERR) [May 27 01:21:37] STEP Run image [quay.io/biocontainers/adam:1.0--hdfd78af_0] with command [[bash -c '/usr/local/env-execute true && . /usr/local/env-activate.sh && adam-submit --help']]
...
2022-05-27T01:21:38.7490797Z INFO:bioconda_utils.utils:(ERR) [May 27 01:21:38] SERR WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/usr/local/lib/python3.10/site-packages/pyspark/jars/spark-unsafe_2.11-2.4.4.jar) to method java.nio.Bits.unaligned()
...
2022-05-27T01:21:39.2995856Z INFO:bioconda_utils.utils:(ERR) [May 27 01:21:39] SERR Exception in thread "main" java.lang.NoSuchMethodError: 'void scala.Product.$init$(scala.Product)'
```
This latter `NoSuchMethodError` occurs when running code built against Scala 2.12 on Scala 2.11 at runtime.

This version installed earlier in the CI run is correct
```
2022-05-27T01:13:00.3367278Z 01:13:00 BIOCONDA INFO (OUT)     py4j:                      0.10.9.3-pyhd8ed1ab_1      conda-forge
2022-05-27T01:13:00.3367913Z 01:13:00 BIOCONDA INFO (OUT)     pyarrow:                   8.0.0-py310h225c066_1_cpu  conda-forge
2022-05-27T01:13:00.3368609Z 01:13:00 BIOCONDA INFO (OUT)     pyspark:                   3.2.1-pyhd8ed1ab_0         conda-forge
2022-05-27T01:13:00.3369243Z 01:13:00 BIOCONDA INFO (OUT)     python:                    3.10.4-h9a8a25e_0_cpython  conda-forge
```

Do I need to add version restrictions to the `pyspark` dependency?  We have not needed them before.

**Comment by heuermh** [comment]
@bioconda/core Sorry for the ping, but I'm not sure what to do here

**Comment by bgruening** [comment]
> INFO:bioconda_utils.utils:(ERR) [Jun 10 21:57:24] SERR Exception in thread "main" java.lang.NoSuchMethodError: 'void scala.Product.$init$(scala.Product)'
21:57:24 BIOCONDA INFO (ERR) [Jun 10 21:57:24] SERR Exception in thread "main" java.lang.NoSuchMethodError: 'void scala.Product.$init$(scala.Product)'
INFO:bioconda_utils.utils:(ERR) [Jun 10 21:57:24] SERR at org.bdgenomics.adam.cli.CommandGroup.<init>(ADAMMain.scala:69)
21:57:24 BIOCONDA INFO (ERR) [Jun 10 21:57:24] SERR at org.bdgenomics.adam.cli.CommandGroup.<init>(ADAMMain.scala:69)
21:57:24 INFO:bioconda_utils.utils:(ERR) [Jun 10 21:57:24] SERR at org.bdgenomics.adam.cli.ADAMMain$.<init>(ADAMMain.scala:44)
BIOCONDA INFO (ERR) [Jun 10 21:57:24] SERR at org.bdgenomics.adam.cli.ADAMMain$.<init>(ADAMMain.scala:44)


Seems there are some errors in the created container. This looks relevant "Unable to load native-hadoop library for your platform". See here: https://dev.azure.com/bioconda/25074ded-3133-43ca-af80-895ab87b53cb/_apis/build/builds/17458/logs/21

**Comment by heuermh** [comment]
Thank you, @bgruening!

The container and non-container versions of the CI build appear to be using different versions of Spark + Scala.

ADAM only works with Spark 3.2.1 and Scala 2.12; the container build is using Spark 2.4.4 and Scala 2.11 for some reason.

**Comment by heuermh** [comment]
@BiocondaBot please add label

**Review by cbrueffer — APPROVED** [review]

**Comment by cbrueffer** [comment]
@bioconda-bot please merge

**Comment by heuermh** [comment]
Thank you, @cbrueffer!
